#include "safetylogic.h"
#include <QtTest>
class SafetyLogicTest:public QObject{
Q_OBJECT
private slots:
void countsEveryVehicle(){OccupancyTracker t;QVERIFY(t.enter(101));QVERIFY(t.enter(102));QVERIFY(!t.enter(101));QCOMPARE(t.count(),2);QVERIFY(t.leave(101));QCOMPARE(t.count(),1);QVERIFY(t.leave(102));QVERIFY(t.clear());}
void slowVehicleExtendsClearance(){QVERIFY(clearanceSeconds(30,9,2,1.5)>clearanceSeconds(30,30,2,1.5));QVERIFY(clearanceSeconds(0,30,2,1.5)>=2);}
void heavyVehicleLengths(){QVERIFY(vehicleLengthMeters(RoadUserKind::ArticulatedTruck)>vehicleLengthMeters(RoadUserKind::Bus));QVERIFY(vehicleLengthMeters(RoadUserKind::Bus)>vehicleLengthMeters(RoadUserKind::Car));}
void heavyVehicleRearStaysLongerInZone(){QVERIFY(normalizedRearGap(RoadUserKind::ArticulatedTruck)>normalizedRearGap(RoadUserKind::Bus));QVERIFY(normalizedRearGap(RoadUserKind::Bus)>normalizedRearGap(RoadUserKind::Car));QVERIFY(normalizedRearGap(RoadUserKind::Car)>normalizedRearGap(RoadUserKind::Bicycle));}
void faultRequiresExplicitSafeReset(){FaultLatch latch;latch.raise();QVERIFY(latch.active());QVERIFY(!latch.reset(false,true));QVERIFY(!latch.reset(true,false));QVERIFY(latch.active());QVERIFY(latch.reset(true,true));QVERIFY(!latch.active());}
void pedestrianCallsAreStoredPerSide(){PedestrianQueue q;q.request(2);q.request(0);q.request(2);QCOMPARE(q.count(),2);QCOMPARE(q.takeNext().value(),0);QCOMPARE(q.takeNext().value(),2);QVERIFY(!q.takeNext().has_value());}
void pedestrianPhaseRequiresClearZoneAndBlocksVehicles(){PedestrianPhase p;QVERIFY(!p.start(false));QVERIFY(p.start(true));QVERIFY(p.blocksVehicleEntry());QCOMPARE(p.stage(),PedestrianStage::Green);}
void pedestrianPhaseEnforcesGreenAndClearance(){PedestrianPhase p;QVERIFY(p.start(true));p.advance(SafetyTiming::PedestrianGreenSeconds-.01);QCOMPARE(p.stage(),PedestrianStage::Green);p.advance(.01);QCOMPARE(p.stage(),PedestrianStage::Clearance);p.advance(SafetyTiming::PedestrianClearanceSeconds,true);QCOMPARE(p.stage(),PedestrianStage::Clearance);p.advance(0,false);QCOMPARE(p.stage(),PedestrianStage::Idle);QVERIFY(!p.blocksVehicleEntry());}
void everyApproachUsesLeftOnlyAndStraightRightLanes(){for(int side=0;side<4;side++){auto a=Approach(side);QCOMPARE(allowedMask(a,0),movementBit(Maneuver::Left));QCOMPARE(allowedMask(a,1),movementBit(Maneuver::Straight)|movementBit(Maneuver::Right));}}
void conflictsMatchConservativeIntersectionModel(){QVERIFY(movementsCompatible(Approach::North,Maneuver::Straight,Approach::South,Maneuver::Straight));QVERIFY(!movementsCompatible(Approach::North,Maneuver::Left,Approach::South,Maneuver::Left));QVERIFY(!movementsCompatible(Approach::North,Maneuver::Left,Approach::South,Maneuver::Straight));QVERIFY(movementsCompatible(Approach::North,Maneuver::Right,Approach::East,Maneuver::Right));QVERIFY(!movementsCompatible(Approach::North,Maneuver::Straight,Approach::East,Maneuver::Right));}
void pedestrianCompatibilityChecksEveryMovementInTheLane(){QVERIFY(movementConflictsWithCrossing(Approach::North,Maneuver::Straight,Approach::North));QVERIFY(movementConflictsWithCrossing(Approach::South,Maneuver::Straight,Approach::North));QVERIFY(!movementConflictsWithCrossing(Approach::East,Maneuver::Straight,Approach::North));QVERIFY(!laneGroupCompatibleWithCrossing(int(Approach::North)*2+0,Approach::North));QVERIFY(laneGroupCompatibleWithCrossing(int(Approach::East)*2+0,Approach::North));}
void timingMatchesVerifiedWebDefaults(){QCOMPARE(SafetyTiming::AllRedSeconds,1.2);QCOMPARE(SafetyTiming::RedYellowSeconds,.9);QCOMPARE(SafetyTiming::MinimumVehicleGreenSeconds,4.0);QCOMPARE(SafetyTiming::VehicleYellowSeconds,3.0);QCOMPARE(SafetyTiming::PedestrianGreenSeconds,5.0);QCOMPARE(SafetyTiming::PedestrianClearanceSeconds,13.5);}
void constructionNeverReversesWhileOccupied(){ConstructionState state;ConstructionTiming timing;ConstructionInputs input;input.masterDemand=1;input.slaveDemand=1;state=advanceConstruction(state,input,timing,timing.allRed);QCOMPARE(state.stage,ConstructionStage::Green);auto first=state.active;input.corridorOccupied=true;input.masterDemand=0;input.slaveDemand=5;state=advanceConstruction(state,input,timing,30);QCOMPARE(state.stage,ConstructionStage::Green);QCOMPARE(state.active,first);QVERIFY(constructionSafe(state));}
void constructionRadioLossLatchesFault(){ConstructionState state;ConstructionTiming timing;ConstructionInputs input;input.linkOnline=false;state=advanceConstruction(state,input,timing,.1);QCOMPARE(state.stage,ConstructionStage::Fault);QVERIFY(state.faultLatched);input.linkOnline=true;state=advanceConstruction(state,input,timing,10);QCOMPARE(state.stage,ConstructionStage::Fault);input.resetFault=true;state=advanceConstruction(state,input,timing,.1);QCOMPARE(state.stage,ConstructionStage::AllRed);QVERIFY(!state.faultLatched);QVERIFY(constructionSafe(state));}
void constructionRandomizedRunAlwaysStaysSafe(){ConstructionState state;ConstructionTiming timing;for(int step=0;step<10000;step++){ConstructionInputs input;input.masterDemand=step%4;input.slaveDemand=step%7;input.corridorOccupied=step%41==0;input.emergency=step%997==0;input.resetFault=!input.emergency&&state.faultLatched&&step%13==0;state=advanceConstruction(state,input,timing,.1);QVERIFY(constructionSafe(state));}}
void movementCompatibilityIsSymmetric(){for(int a=0;a<4;a++)for(int ma=0;ma<3;ma++)for(int b=0;b<4;b++)for(int mb=0;mb<3;mb++)QCOMPARE(movementsCompatible(Approach(a),Maneuver(ma),Approach(b),Maneuver(mb)),movementsCompatible(Approach(b),Maneuver(mb),Approach(a),Maneuver(ma)));}
};QTEST_MAIN(SafetyLogicTest)
#include "test_safetylogic.moc"
